name: Deploy Migrations

on:
  push:
    branches:
      - master
    # paths:
    #   - 'Migrations/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download flyway
        run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.1/flyway-commandline-8.5.1-linux-x64.tar.gz | tar xvz && sudo ln -s pwd/flyway-8.5.1/flyway /usr/local/bin
      - name: extract and link flyway
        run: tar -xvf flyway-commandline-8.5.1-linux-x64.tar.gz && sudo ln -s pwd/flyway-8.5.1/flyway /usr/local/bin
      - name: migrate master
        if: github.ref == 'refs/heads/master'
        run: flyway -url='${{ secrets.DEV_DB_URL }}' -user=${{ secrets.DEV_DB_USER }} -password=${{ secrets.DEV_DB_PASSWORD }} -locations=filesystem:./Migrations -outOfOrder=true -baselineOnMigrate=true migrate